import Head from 'next/head'
import { useRecoilState, useRecoilValue } from 'recoil'
import { Box, Button, Container, Heading, Text} from '@chakra-ui/react'
import { AddIcon } from '@chakra-ui/icons'

import { todosState } from './atoms/atom'
import TodoList from './components/TodoList'
import Search from './components/Search'
import Link from 'next/link'

export default function Home() {
  const todos = useRecoilValue(todosState);
  console.log("現在のTodos：",todos);

  return (
    <>
      <Head>
        <title>Todo App Team3</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container h='100%' minH='100%' maxW='100%' bg='orange.100' m='0' padding='1rem'>
        <Heading pt='2' pb='2' pl='5' bg='orange.200'>
          Todo App
        </Heading>

        <Container minH='calc(100% - 64px)' maxW='100%' bg='white' padding='5'>
          <Text fontSize='lg' fontWeight='bold' letterSpacing='3px'>
            {todos.length >= 1 ? `タスクは${todos.length}個あります` : '現在タスクはありません'}
          </Text>

          <Search />

          <Box mt='10' mr='5' textAlign='right'>
            <Link href="./addtask">
            <Button>
              <AddIcon mr='2' />
              タスクを追加
            </Button>
            </Link>
          </Box>

          <TodoList />
        </Container>
      </Container>
    </>
  )
}