import Head from 'next/head'
import { useState, useEffect } from 'react'
import { useRecoilValue } from 'recoil'
import { Box, Button, Container, Heading, Text} from '@chakra-ui/react'
import { AddIcon } from '@chakra-ui/icons'

import { todosState } from './atoms/atom'
import TodoList from './components/TodoList'
import Search from './components/Search'
import Link from 'next/link'

export default function Home() {
  const todos = useRecoilValue(todosState);
  const [priority, setPriority] = useState("全て");
  const [status, setStatus] = useState("全て");
  const [inputFilter, setInputFilter] = useState(null);
  const [searchTodos, setSearchTodos] = useState([]);

  useEffect(() => {
    if (priority === "全て" && status === "全て" && !inputFilter) {
      setSearchTodos(null);
    } else {
      if (priority !== "全て" && status !== "全て") {
        setSearchTodos(
          todos.filter((todo) => {
            return todo.priority === priority && todo.status === status ? true : false;
          })
        )
      } else  {
        setSearchTodos(
          todos.filter((todo) => {
            return todo.priority === priority || todo.status === status ? true : false;
          })
        )
      }

      if (inputFilter) {
        const filterList = todos.filter((todo) => (
          todo.title.toString().indexOf(inputFilter) >= 0
        ));
        setSearchTodos(filterList);
      }
    }
  }, [status, priority, inputFilter, todos])

  return (
    <>
      <Head>
        <title>Todo App Team3</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container minH='100%' maxW='100%' bg='orange.100' m='0' padding='1rem'>
        <Box px="5" bg='orange.200'>
          <Heading pt='2' pb='2'maxWidth="1100px" mx="auto" >
            Todo App
          </Heading>
        </Box>

        <Container minH='calc(100vh - 90px)'  maxW='100%' bg='white' padding={[0,0,4]}>
          <Box maxWidth="1100px" mx="auto" >
            <Text fontSize={['sm','lg']} fontWeight='bold' letterSpacing='3px' p={[1,2]}>
              {todos.length >= 1 ? `タスクは${todos.length}個あります` : '現在タスクはありません'}
            </Text>
            <Search 
            setStatus={setStatus}
            setPriority={setPriority}
            setInputFilter={setInputFilter}/>
            <Box mt='5' mr={[2,2,0]} textAlign='right'>
              <Link href="/addtask">
              <Button fontSize={['sm','md']}>
                <AddIcon mr='2' />
                タスクを追加
              </Button>
              </Link>
            </Box>
            <TodoList 
            searchTodos={searchTodos}
            />
          </Box>
        </Container>
      </Container>
    </>
  )
}