import Head from 'next/head';
import Link from "next/link";
import { useRouter } from 'next/router';
import { useRecoilValue } from 'recoil';
import {
  Box,
  Container,
  Stack,
  Flex,
  Spacer,
  Divider,
  Button,
} from '@chakra-ui/react';

import { todosState } from '../atoms/atom';

export default function Detail() {
  const router = useRouter();
  const todos = useRecoilValue(todosState);
  
  const todo = todos.filter((todo) => {
    return todo.id === Number(router.query.id)
  })

  return (
    <>
      <Head>
        <title>-Detail- Todo Team Dev No.3</title>
        <meta name="description" content="Generated by create nextapp" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        pos="fixed"
        lineHeight="48px"
        color="white"
        w="full"
        h={12}
        top={0}
        fontSize="28px"
        zIndex={2}
        bg="#829098"
      >
        <Container maxW="container.lg">Todo アプリ</Container>
      </Box>
      <Container mt={["80px","110px"]} maxW="container.lg">
        <Stack spacing={[2,8]}>
          <Flex direction={["column","row"]}>
            <Flex w={24} minW={24}>
              <Box>タスク名</Box>
              <Spacer />
              <Box>:</Box>
            </Flex>
            {/* useRouter 使用時、１回目にundefinedが入りエラーを起こす為、オプショナルチェーンでundefinedを許可。 */}
            <Box ml={[0,8]}>{todo[0]?.title}</Box>
          </Flex>
          <Divider borderColor='gray' borderBottomWidth='2px' />
          <Flex minH={44} direction={["column","row"]}>
            <Flex w={24} minW={24}>
              <Box>内容</Box>
              <Spacer />
              <Box>:</Box>
            </Flex>
            <Box ml={[0,8]}>
              {todo[0]?.text}
            </Box>
          </Flex>
          <Divider borderColor='gray' borderBottomWidth='2px' />
          <Flex>
            <Flex w={24} minW={24}>
              <Box>ステータス</Box>
              <Spacer />
              <Box>:</Box>
            </Flex>
            <Box ml={8}>{todo[0]?.status}</Box>
          </Flex>
          <Divider borderColor='gray' borderBottomWidth='2px' />
          <Flex>
            <Flex w={24} minW={24}>
              <Box>優先度</Box>
              <Spacer />
              <Box>:</Box>
            </Flex>
            <Box ml={8}>{todo[0]?.priority}</Box>
          </Flex>
        </Stack>
      </Container>
      <Container maxW="container.lg" pos="fixed" bottom="0">
        <Flex>
          <Spacer/>
          <Link href='/' passHref>
            <Button _hover={{opacity:0.8}} m={4} bg="#84ADC5" color="white" w="80px">
              戻る
            </Button>
          </Link>
        </Flex>
      </Container>
    </>
  );
}
